---
description: ""
experiment_path: experiments/open_cities_smp_unet_binary_focal_dice_075_huge_dataset_300samples_4stable

# Path to folder where must be two folder: `mask`, `img` in our format
data_path: /home/partsey/data/cropped
csv_path: /datasets/rpartsey/open_cities/experiments_data/white_images_with_mask_exists.csv
val_csv_path: /datasets/rpartsey/open_cities/experiments_data/small_val_with_mask_exists.csv
num_loader_workers: 4

chips_per_scene: 10
img_size: &SIZE [1024, 1024]

# Setup random_state for dividing dataset
random_state: 5
train_val_state: 5

# Fraction of dataset to be chosen for validation while training
validation_fraction: 0.2

transformations:
  image:
#    - name: histnorm
#    - name: gray2rgbtriple
#    - name: defaultnorm
#      params:
#        mean: [0.485, 0.456, 0.406]
#        std: [0.229, 0.224, 0.225]
#    - name: bydimnormalise
    - name: fromnumpy
    - name: tofloat
  mask:
#    - name: alltosingleobject
    - name: fromnumpy
    - name: tolong

augmentations:
  p: 0.9
  size: *SIZE

model: # specs for model
    type: smp_unet
    params:
      in_channels: 3
      out_channels: 1
      pretrained: False

# Batch sizes
train_batch_size: 12
val_batch_size: 12

stage1:
  resume_training: False
  model_path: ""
  # Epochs to train
  num_epochs: 100
  loss:
    type: binary_focal_dice
  optimizer: # optimizer params
      # Optim name;
      # Possible values - [adam, sgd, adadelta]
      type: adam
      params:
        lr: 0.0001
  scheduler: # Scheduler configurations. Scheduler is used for Learning rate change
     type: plateau          # Plateau TODO: describe
     params:
       mode: min
       patience: 3
  stopper: # Stops the training if constraints are met
    patience: 70
